name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make Pass
        run: |
          apt install -y libsodium-dev
          make all
          make test